#!/bin/bash

# Provides autocomplete functionality for atau

completion()
{
	local current=${COMP_WORDS[${COMP_CWORD}]}

	# use the below line to export reply.
	#export COMPREPLY=($(compgen -f "foo bar baz"))
}

complete -F completion atau
